<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows10.0.22621.0;net10.0-ios;net10.0-maccatalyst;net10.0-android;net10.0</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <!-- Ensures the .xr.xml files are generated in a proper layout folder. -->
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
    <RootNamespace>Reactive.Annex</RootNamespace>
    <Authors>nventive</Authors>
    <Company>nventive</Company>
    <AssemblyName>Reactive.Annex.Uno.WinUI</AssemblyName>
    <PackageId>Reactive.Annex.Uno.WinUI</PackageId>
    <Description>Reactive.Annex.Uno.WinUI</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>reactive;annex;mvvm;maui;winui;ios;android</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/nventive/Reactive.Annex</PackageProjectUrl>
    <DefineConstants>$(DefineConstants);WINUI</DefineConstants>

    <!-- This is needed for Source Link support. -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Uno.WinUI" Version="6.3.62" />
  </ItemGroup>

  <ItemGroup>
    <!-- This is needed for Source Link support. -->
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.102" PrivateAssets="All" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net10.0'">
    <DefineConstants>$(DefineConstants);__WASM__</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net10.0-windows10.0.22621.0'">
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250606001" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net10.0-windows10.0.22621.0'">
    <WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>

    <!-- 
      Needed to use unsafe code for interop with WinRT.

      WinRT.SourceGenerator\Generator.WinRTAotSourceGenerator\WinRTGenericInstantiation.g.cs(450,31,450,48):
        error CS0227: Unsafe code may only appear if compiling with /unsafe
    -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'!='net10.0-windows10.0.22621.0'">
    <Page Include="**\*.xaml" Exclude="bin\**\*.xaml;obj\**\*.xaml" />
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Include="**\*.xaml" Exclude="bin\**\*.xaml;obj\**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="4.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reactive.Annex\Reactive.Annex.csproj" />
  </ItemGroup>

  <Import Project="..\Reactive.Annex.Shared\Reactive.Annex.Shared.projitems" Label="Reactive.Annex.Shared" />
</Project>